export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_DATE_FROM = 'SET_SEARCH_DATE_FROM';
export const SET_SEARCH_DATE_UNTIL = 'SET_SEARCH_DATE_UNTIL';

export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
