export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_DATE_FROM = 'SET_SEARCH_DATE_FROM';
export const SET_SEARCH_DATE_UNTIL = 'SET_SEARCH_DATE_UNTIL';
export const SET_DATE_FILTER_VALUE = 'SET_DATE_FILTER_VALUE';
export const DIALOG_OPEN = 'DIALOG_OPEN'; 
export const DIALOG_CLOSE = 'DIALOG_CLOSE';
export const SET_DIALOG_DATE_FROM = 'SET_DIALOG_DATE_FROM';
export const SET_DIALOG_DATE_UNTIL = 'SET_DIALOG_DATE_UNTIL';

export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
