export const SET_PUBLISH_DESCRIPTION = 'SET_PUBLISH_DESCRIPTION';
export const SET_PUBLISH_MAGNET_LINK = 'SET_PUBLISH_MAGNET_LINK';


export const PUBLISH_PENDING = 'PUBLISH_PENDING';
export const PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
export const PUBLISH_FAIL = 'PUBLISH_FAIL';
