export const SET_SUBSCRIPTION_ADDRESS = 'SET_SUBSCRIPTION_ADDRESS';

export const UPDATE_INDEX_PENDING = 'UPDATE_INDEX_PENDING';
export const UPDATE_INDEX_SUCCESS = 'UPDATE_INDEX_SUCCESS';
export const UPDATE_INDEX_FAIL = 'UPDATE_INDEX_FAIL';
